FROM timstephens24/ubuntu

# set version label
ARG BUILD_DATE
ARG VERSION
ARG JELLYFIN_RELEASE
LABEL build_version="stephens.cc version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="timstephens24"

# environment settings
ARG DEBIAN_FRONTEND="noninteractive"
ENV NVIDIA_DRIVER_CAPABILITIES="compute,video,utility"

RUN echo "**** install jellyfin *****" \
  && curl -s https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key | apt-key add - \
  && echo 'deb [arch=amd64] https://repo.jellyfin.org/ubuntu focal main' > /etc/apt/sources.list.d/jellyfin.list \
#  && echo 'deb [arch=amd64] https://repo.jellyfin.org/ubuntu focal unstable' >> /etc/apt/sources.list.d/jellyfin.list \
  && apt-get update \
#  && apt-get install -y --no-install-recommends jellyfin-ffmpeg jellyfin \
  && curl -o /tmp/jellyfin.deb -L \
    https://repo.jellyfin.org/releases/server/debian/stable-rc/server/jellyfin-server_10.7.0~rc4_amd64.deb \
  && curl -o /tmp/jellyfin-web.deb -L \
    https://repo.jellyfin.org/releases/server/debian/stable-rc/web/jellyfin-web_10.7.0~rc4_all.deb \
  && dpkg -i /tmp/jellyfin-web.deb \
  && dpkg -i /tmp/jellyfin.deb \
  && echo "**** cleanup ****" \
  && rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*

# add local files
COPY root/ /

# ports and volumes
EXPOSE 8096 8920
VOLUME /config
